name: _reusable commitlint workflow

on:
  workflow_call:

jobs:
  commitlint:
    name: Lint commits
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: './commitlint.config.ts'
